### ISSUE TITLE
编译后的目录结构和服务器部署结构不一致如何配置

### ISSUE THREAD

**Issue by tjuking** [fex-team/fis3-deploy-http-push#12]
在fisp里可以配置模板、静态资源等到不同的发布路径，但是在fis3里没找到如何配置。

**Comment by oxUnd** [comment]
可以这样

``` js
fis.match('/static/**', {
  deploy: fis.plugin('http-push', {
    receiver: 'xxxx',
    to: '/xxxx/a'
   })
});

fis.match('*.tpl', {
   deploy: fis.plugin('http-push', {
    receiver: 'xxxx',
    to: '/xxxx/b'
   })
});
```

**Comment by dblate** [comment]
我的解决方法是：
`const deployServer = {
    test: {
        host: '10.99.203.176',
        port: 8220
    }
};

const deployPath = [{
    from: '/page/**',
    to: '/home/work/orp/template/wiki-second'
}, {
    from: '/static/**',
    to: '/home/work/orp/webroot'
}, {
    from: '/pkg/**',
    to: '/home/work/orp/webroot'
}, {
    from: '/modules/**',
    to: '/home/work/orp/webroot'
}, {
    from: '/wiki-second-map.json',
    to: '/home/work/orp/data/smarty'
}];

fis.util.map(deployServer, function (serverName, serverConfig) {
    deployPath.forEach(function (path) {
        fis.media(serverName)
            .match(path.from, {
                deploy: fis.plugin('http-push', {
                    receiver: 'http://' + serverConfig.host + ':' + serverConfig.port + '/receiver.php',
                    to: path.to
                })
            });
    })
});`
不知道还有没有更好的方式

**Comment by dblate** [comment]
```javascript
        test
````

**Comment by dblate** [comment]
我是这么处理的，不知道还有没有更好的方式：
```javascript
const deployServer = {
    test: {
        host: '1.1.1.1',
        port: 8080
    }
};

const deployPath = [{
    from: '/page/**',
    to: '/xxxx/a'
}, {
    from: '/static/**',
    to: '/xxxx/b'
}, {
    from: '/pkg/**',
    to: '/xxxx/c'
}];

fis.util.map(deployServer, function (serverName, serverConfig) {
    deployPath.forEach(function (path) {
        fis.media(serverName)
            .match(path.from, {
                deploy: fis.plugin('http-push', {
                    receiver: 'http://' + serverConfig.host + ':' + serverConfig.port + '/receiver.php',
                    to: path.to
                })
            });
    })
});
```
