### ISSUE TITLE
增加其他字段支持

### ISSUE THREAD

**Issue by maxming2333** [fex-team/fis3-deploy-http-push#9]
fork这个库后，我自己扩展了一个功能

其实我感觉这样不妥

要不我弄一个 `Pull requests` ?

项目地址: [https://github.com/maxming2333/fis3-deploy-http-push-plus](https://github.com/maxming2333/fis3-deploy-http-push-plus)

**Comment by 2betop** [comment]
恩，求 pr

**Comment by maxming2333** [comment]
已发pr [#10](https://github.com/fex-team/fis3-deploy-http-push/pull/10)

**Comment by maxming2333** [comment]
Resolved #10

**Comment by maxming2333** [comment]
close
